### ISSUE TITLE
Saved Search Functionality

### ISSUE THREAD

**Issue by easiestripes** [benji300/joplin-favorites#1]
Being able to easily repeat saved searches is a necessary feature for me before I can fully switch to Joplin.
Do you have a topic on the Joplin discourse I can like to increase visibility on it?

**Comment by easiestripes** [comment]
ps thank you for the great work you did on this plugin!

**Comment by benji300** [comment]
Hm... I'm not quite sure if it is that what you mean... but may be one of the following?

**https://discourse.joplinapp.org/t/save-search-query-in-the-left-panel/8435**
https://discourse.joplinapp.org/t/saved-searches/2703

**Comment by easiestripes** [comment]
Ah ok cool, also found your post https://discourse.joplinapp.org/t/notebook-note-to-do-tag-search-favorites-plugin/14049, ill comment on there
