### ISSUE TITLE
After Joplin update to version 2.2.6 pluggin Favorites not working

### ISSUE THREAD

**Issue by stepanpos** [benji300/joplin-favorites#11]
Favorites v1.2.1 in Joplin version 2.2.6 is installed, enabled, but in context menu is no command about this pluggin. The Favorites Pannel missing too.

**Comment by ameisbe** [comment]
after the critical change in Joplin was rolled back in version 2.2.7 most of my broken plugins worked again. 
My favorite plugin "Favorites" though still seems to be broken. 
Thanks for your great work an full understanding if fixing the problem will take time.

**Comment by benji300** [comment]
The plugin stopped working due to an breaking change in the plugin API introduced with Joplin v2.2.4.
It is fixed with the latest version of the plugin [v1.3.0](https://github.com/benji300/joplin-favorites/releases/tag/v1.3.0).

**Comment by nablabits** [comment]
Thank you ✨
