### ISSUE TITLE
How to set background color same as sidebar

### ISSUE THREAD

**Issue by AntoinePrv** [benji300/joplin-favorites#16]
Hello,

New to Joplin here, thanks for this plugin. It ,looks very useful.
In the preferences, the background color is set to `default`. How can I have it be the same as the sidebar as in the [README](https://github.com/benji300/joplin-favorites#favorites-in-sidebar-vertical-layout) ?
I tried setting the value to `sidebar` or similar but couldn't find any correct value.

**Comment by benji300** [comment]
Hi @AntoinePrv,

thanks for your feedback 😀 

I've added a description to the [README](https://github.com/benji300/joplin-favorites#match-with-sidebar-look). It describes how to set the options to get the same look as the sidebar itself. 
Unfortunately its not that intuitive, you have to enter some special CSS values...

For references see also [here](https://discourse.joplinapp.org/t/notebook-note-to-do-tag-search-favorites-plugin/14049/8).
