### ISSUE TITLE
Update version in `manifest.json`

### ISSUE THREAD

**Issue by personalizedrefrigerator** [benji300/joplin-favorites#28]
It looks like `manifest.json` still has the old version of the plugin:

https://github.com/benji300/joplin-favorites/blob/4dac48d9429d7f05d86badb32a3f283da93afb5a/src/manifest.json#L5

This line should be updated to allow users to update to the new version.

(Thank you @benji300 for providing an update for this plugin!)

**Comment by benji300** [comment]
yeah, I've missed that. Created new v1.3.2 release.

**Comment by personalizedrefrigerator** [comment]
I can download the updated version now.

Thank you for your work!

**Comment by laurent22** [comment]
Thanks for releasing that new version @benji300, much appreciated!
