### ISSUE TITLE
Handle target favorite folder tree when collapsed

### ISSUE THREAD

**Issue by markrenier** [benji300/joplin-favorites#5]
Great plug-in! 

Summary: 
When I click on a favorite, the favorited folder gets focus, but if that folder is enclosed in a collapsed hierarchy tree, I can't see the folder I jumped to. 

Situation: 
I use a lot of folders and sub-folders, and collapse them/open them as needed. When I have favorited a folder, and that folder is itself inside another folder, I can't see it when I use this plug-in by clicking on the link. When I open the enclosing folder, I can indeed see that the folder is highlighted and active. I would like the plug-in to un-fold the hierarchy of folders that enclose  the target folder, just as Joplin itself does, when I search for a task, find a hit, then click on the enclosing folder link. 

Thanks!

**Comment by benji300** [comment]
Unfortunately this is something I can't change in the plugin. I'm just triggering an internal command (`openFolder`) to open the folder. So this issue should be addressed to the core App.
